version: "3.7"

volumes:
  postgres:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /opt/postgresql/backup:/var/lib/postgresql/backup
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"