version: "3.1"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    volumes:
      - /opt/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always